# Generated by Django 5.0.1 on 2025-02-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
