# Generated by Django 5.0.1 on 2025-04-09 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('AD', 'Admin'), ('US', 'User'), ('LB', 'Librarian')], default='US', max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.svg', null=True, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('category', models.CharField(choices=[('CK', 'Cooking'), ('CR', 'Crime'), ('MY', 'Mistery'), ('SF', 'Science Fiction'), ('FAN', 'Fantasy'), ('HIS', 'History'), ('ROM', 'Romance'), ('TXT', 'Textbook')], max_length=3)),
                ('language', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('NW', 'New'), ('GD', 'Good'), ('FR', 'Fair'), ('PO', 'Poor')], max_length=4)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(default='static/images/library_seal.jpg', upload_to='images/')),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('copy_number', models.IntegerField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_books', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
