# Generated by Django 5.0.1 on 2025-03-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('numberbooks', models.IntegerField()),
                ('type', models.CharField(choices=[('AD', 'Admin'), ('US', 'User'), ('LB', 'Librarian')], max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('category', models.CharField(choices=[('CK', 'Cooking'), ('CR', 'Crime'), ('MY', 'Mistery'), ('SF', 'Science Fiction'), ('FAN', 'Fantasy'), ('HIS', 'History'), ('ROM', 'Romance'), ('TXT', 'Textbook')], max_length=3)),
                ('language', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('NW', 'New'), ('GD', 'Good'), ('FR', 'Fair'), ('PO', 'Poor')], max_length=4)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(default='static/images/library_seal.jpg', upload_to='images/')),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('copy_number', models.IntegerField(blank=True, null=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to='backend.people')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.people')),
            ],
        ),
    ]
