# Generated by Django 5.0.1 on 2025-03-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/library_seal.jpg', upload_to='images/'),
        ),
    ]
