# Generated by Django 5.0.1 on 2025-03-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='static/images/library_seal.jpg', upload_to='images/'),
        ),
    ]
