# Generated by Django 5.0.1 on 2025-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_book_borrow_date_book_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copy_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='storage_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
